ConnectIT.Web/Controllers/FriendRequestController.cs
using ConnectIT.Services.Contracts;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ConnectIT.Web.Controllers
{
    public class FriendRequestController : Controller
    {
        private readonly IFriendRequestService friendRequestService;
        private readonly IUserService userService;
        public readonly IFriendService friendService;

        public FriendRequestController(IFriendRequestService friendRequestService, IUserService userService,IFriendService friendService)
        {
            this.friendRequestService = friendRequestService;
            this.userService = userService;
            this.friendService = friendService;
        }

        [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
        public IActionResult Index()
        {

            var userId = User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier).Value;

            var users = friendRequestService.GetFriendRequests(userId);

            return View(users);

        }


        public IActionResult AddFriend(string senderId, string receiverId)
        {

            senderId= User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier).Value;

            if (this.friendService.Exists(senderId, receiverId))
            {
                TempData["message"] = "This user is already in your friendlist";
            }

            else
            {
                if (this.friendRequestService.Exists(senderId, receiverId))
                {
                    TempData["message"] = "You have already sent friend request to this user";
                }

                else
                {
                    if (this.friendRequestService.Exists(receiverId, senderId))
                    {
                        TempData["message"] = "This user has already sent you friendrequest.Please check your friendrequest page";
                    }
                    else
                    {
                        TempData["message"] = "FriendRequest sent";
                        this.friendRequestService.Create(senderId, receiverId);
                    }
                }
            }
           
            return RedirectToAction("Details","Users", new { id= receiverId });
        }

        public IActionResult Accept(string senderId, string receiverId)
        {
            TempData["message"] = "Added new Friend";
            this.friendRequestService.Accept(senderId, receiverId);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Decline(string senderId, string receiverId)
        {
            TempData["message"] = "Friendship Declined";
            this.friendRequestService.Decline(senderId, receiverId);
            return RedirectToAction(nameof(Index));
        }

  

    }
}

ConnectIT.Web/Controllers/UsersController.cs
using ConnectIT.DataTransfer;
using ConnectIT.Services.Contracts;
using ConnectIT.Web.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Linq;

namespace ConnectIT.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService userService;

        public UsersController(IUserService userService)
        {
            this.userService = userService;
        }

        public IActionResult Index(UserListModel model, string searchBy, string searchString)
        {
            if (model == null)
            {
                model = new UserListModel();
            }
            model.Users = this.userService.GetUsers().Select(user => new UserSummaryModel(user));

            if (searchBy == "Name")
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    model.Users = model.Users.Where(s => s.FullName.ToLower().Contains(searchString.ToLower()));
                }
            }

            if (searchBy == "Job")
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    model.Users = model.Users.Where(t => t.Job != null && t.Job.ToLower().Contains(searchString.ToLower()));
                }
            }

            return View(model);
        }

        public IActionResult Details(string id)
        {
            var dto = this.userService.GetUserById(id);
            var model = new UserSummaryModel(dto);
            return View(model);
        }

        // GET: users/list
        [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
        [Authorize(Roles = "admin"), HttpGet]
        public IActionResult List()
        {
            var users = this.userService.GetUsersIncludingDeleted();

            return View(users);
        }

        [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
        [Authorize(Roles = "admin")]
        public IActionResult DeleteUser([FromForm] string userId)
        {
            this.userService.DeleteUser(userId);
            return RedirectToAction(nameof(List));
        }

        [Authorize(Roles = "admin")]
        public IActionResult RestoreUser(string userId)
        {
            this.userService.RestoreUser(userId);
            return RedirectToAction(nameof(List));
        }

        [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
        [Authorize(Roles = "admin")]
        public IActionResult Edit(string Id)
        {
            var dto = userService.GetOneUserbyId(Id);
            var model = new UserEditModel(dto);

            return View(model);
        }

        [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "admin")]
        public IActionResult Edit(string Id, UserDetail model)
        {
            if (ModelState.IsValid)
            {

                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var dataStream = new MemoryStream())
                    {
                        file.CopyTo(dataStream);

                        model.ProfilePhoto = dataStream.ToArray();

                    }
                }

                userService.UpdateUser(model);
                TempData["message"] = "User Details Updated";
                return RedirectToAction("Edit");
            }

            return View(model);
        }
    }
}

ConnectIT.Web/Views/Users/Details.cshtml
@using System.Security.Claims;
@model UserSummaryModel

@if (@TempData["message"] != null)
{
    <div class="alert alert-info" role="alert">@TempData["message"]</div>
}

<style>

    .main-body {
        padding: 15px;
    }

    .card {
        box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid rgba(0,0,0,.125);
        border-radius: .25rem;
    }

    .card-body {
        flex: 1 1 auto;
        min-height: 1px;
        padding: 1rem;
    }

    .gutters-sm {
        margin-right: -8px;
        margin-left: -8px;
    }

        .gutters-sm > .col, .gutters-sm > [class*=col-] {
            padding-right: 8px;
            padding-left: 8px;
        }

    .mb-3, .my-3 {
        margin-bottom: 1rem !important;
    }

    .bg-gray-300 {
        background-color: #e2e8f0;
    }

    .h-100 {
        height: 100% !important;
    }

    .shadow-none {
        box-shadow: none !important;
    }
</style>
@{
    var currentUserId = User.Identity.IsAuthenticated ? User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier).Value : "anonymous";
}
<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            @if (Model.ProfilePhoto != null && (Model.AreDetailsVisibleToUser(currentUserId) || Model.Id == currentUserId))
                            {
                                <img class="col-4 border rounded" src="data:image;base64, @Convert.ToBase64String(Model.ProfilePhoto)" />
                            }
                            <div class="mt-3">
                                <h4>@Model.FullName</h4>
                                <p class="text-secondary mb-1">@Model.Job</p>
                                @if (User.Identity.IsAuthenticated && Model.Id != currentUserId)
                                {
                                    <a asp-controller="FriendRequest" asp-action="AddFriend" asp-route-receiverId="@Model.Id" class="btn btn-success btn-sm">Add Friend</a>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @if ((Model.AreDetailsVisibleToUser(currentUserId) || Model.Id == currentUserId))
                                {
                                  @Model.Email
                                }
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Nationality</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @if ((Model.AreDetailsVisibleToUser(currentUserId) || Model.Id == currentUserId))
                                {
                                    @if (Model.Nationality != null)
                                    {
                                        @Model.Nationality;
                                    }
                                }
                                </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">BirthDate</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                @if ((Model.AreDetailsVisibleToUser(currentUserId) || Model.Id == currentUserId))
                                {
                                    @if (Model.BirthDate.Date > DateTime.Parse("1888-02-02"))
                                    {
                                        @Model.BirthDate.ToShortDateString()
                                    }

                                }
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ConnectIT.Web/Views/Users/Edit.cshtml
@model ConnectIT.Web.Models.UserEditModel
@{
    ViewData["Title"] = "Edit User Profile";

}

@if (@TempData["message"] != null)
{
    <div class="alert alert-info" role="alert">@TempData["message"]</div>
}

<h4>@ViewData["Title"]</h4>

<form id="profile-form" method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-6">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job"></label>
                <input asp-for="Job" class="form-control" />
                <span asp-validation-for="Job" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nationality"></label>
                <input asp-for="Nationality" class="form-control" />
                <span asp-validation-for="Nationality" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDate"></label>
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="form-check form-check-inline">
                    <input asp-for="HideProfileDetails" class="form-check-input" />
                    <label asp-for="HideProfileDetails" class="form-check-label"></label>
                </div>
            </div>
            <div class="btn-group" role="group" aria-label="First group">
                <a asp-action="List" class="btn btn-secondary">Back to List</a>
            </div>

            <div class="btn-group" role="group" aria-label="Second group">
                <button id="update-profile-button" type="submit" class="btn btn-primary">Save Changes</button>
            </div>

        </div>
        <div class="col-md-6">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ProfilePic" style="width: 100%;"></label>
                @if (Model.ProfilePic != null)
                {
                    <img id="profilePicture" style="width:350px;height:350px; object-fit:cover" src="data:image/*;base64,@(Convert.ToBase64String(Model.ProfilePic))">
                }
                else
                {
                    <img id="profilePicture" style="width:350px;height:350px; object-fit:cover" src="">
                }
                <input type="file"
                       accept=".png,.jpg,.jpeg,.gif,.tif"
                       asp-for="ProfilePic"
                       class="form-control"
                       style="border:0px!important;padding: 0px;padding-top: 10px;padding-bottom: 30px;"
                       onchange="document.getElementById('profilePicture').src = window.URL.createObjectURL(this.files[0])" />
                <span asp-validation-for="ProfilePic" class="text-danger"></span>
            </div>
        </div>

    </div>
</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ConnectIT.Web/Views/Users/Index.cshtml
@using System.Security.Claims;

@model UserListModel

@{
    ViewData["Title"] = "All Users";
}

<div class="row justify-content-lg-between align-items-baseline">
    <form asp-action="Index" method="get" id="search" class="col-10 mb-2 form-row">
        <div class="input-group col">
            <div class="input-group-prepend">
            </div>
            <input type="text" name=searchString asp-for=FullName class="form-control rounded-right" />
            <button type="submit" form="search" value="Submit" class="btn btn-info">Search</button>

        </div>
        <fieldset>
            <div class="form-check">
                <input type="radio" class="form-check-input" value="Job" id="Job" name="searchBy" checked>
                <label class="form-check-label" for="Job">Job</label>
            </div>
            <div class="form-check">
                <input type="radio" class="form-check-input" value="Name" id="FullName" name="searchBy" checked />
                <label class="form-check-label" for="FullName">Name</label>
            </div>
        </fieldset>
    </form>
</div>
@if (Model.Users.Any())
{
    var currentUserId = User.Identity.IsAuthenticated ? User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier).Value : "anonymous";

    <div class="card-deck">
        @foreach (var item in Model.Users)
        {
            <div class="card mb-4" style="min-width:252px;max-width:252px">
                @if (item.ProfilePhoto != null && ((item.AreDetailsVisibleToUser(currentUserId)||item.Id==currentUserId)))
                {
                    <img class="card-img-top preview-md" src="data:image;base64,@Convert.ToBase64String(item.ProfilePhoto)" alt="User Image">
                }
                else
                {
                    <img class="card-img-top preview-md" src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" width="0" height="0" alt="" />
                }
                <div class="card-body">
                    <h4 style="  color: #2F4F4F;" class="card-title">@Html.DisplayFor(modelItem => item.FirstName) @Html.DisplayFor(modelItem => item.LastName)</h4>
                    <h6 style="  color: #87CEFA;" class="card-title">@Html.DisplayFor(modelItem => item.Job)</h6>
                </div>
                <div class="card-footer">
                    @Html.ActionLink("View Profile", "Details", new { Id = item.Id }, new { @class = "btn btn-outline-info float-right" })
                </div>
            </div>
        }
    </div>
}
else
{
    <h4 class="rounded border bg-info text-white p-3 text">No Users found. Try changing search criteria.</h4>
}

ConnectIT.Web/Views/Users/List.cshtml
@model IEnumerable<ConnectIT.DataTransfer.UserDetail>
@using System.Security.Claims

@{
    ViewData["Title"] = "List";
}

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Email)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Where(x=>x.Id!= (User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier).Value)))
        {
            <tr class="@(user.IsDeleted ? "bg-danger" : "")">
                <td>@Html.DisplayFor(modelItem => user.Email)</td>
                <td>
                    <button type="button" data-user="@user.Id" class="btn btn-warning" onclick="deleteUser(this)">Delete</button>
                    <a asp-controller="Users" asp-action="RestoreUser"
                       asp-route-userId="@user.Id"
                       class="btn btn-warning">Restore</a>
                    <a asp-controller="Users" asp-action="Edit"
                       asp-route-Id="@user.Id"
                       class="btn btn-warning">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>




<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Deleting User</h5>
            </div>
            <div class="modal-body">
                <form id="ban-form" asp-action="DeleteUser" method="post">
                    <input id="userId" name="userId" type="hidden" />
                    <div class="form-group">
                        <label class="control-label">Are you sure you want to delete this user?</label>
                        <small class="form-text text-muted">
                            <br />User will be deleted as of now
                        </small>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary" form="ban-form" value="Submit">Confirm Delete</button>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script type="text/javascript">

        function deleteUser(element) {
            //display modal
            $('#delete-modal').modal('show');
            // set userid in formn
            var userId = $(element).data("user");
            $('#userId').val(userId);

         }

        
    </script>
}