ConnectIT.Web/Controllers/AdminController.cs
using ConnectIT.Services.Contracts;
using ConnectIT.Web.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace ConnectIT.Web.Controllers
{
    [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme, Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly IPostService postService;
        private readonly ICommentService commentService;
        private readonly IUserService userService;

        public AdminController(IPostService postService, ICommentService commentService, IUserService userService)
        {
            this.postService = postService;
            this.commentService = commentService;
            this.userService = userService;
        }

        [HttpGet("admin/editpost/{id}")]
        public IActionResult EditPost(int id)
        {
            var dto = postService.Get(id);

            var model = new PostEditModel
            {
                Id = dto.Id,
                AuthorId = dto.Author.Id,
                CreatedOn = dto.CreatedOn,
                Content = dto.Content,
                Location = dto.Location,
                Photos = dto.Photos,
                Comments = dto.Comments.Select(x => new CommentInputModel
                {
                    Id = x.Id,
                    PostId = x.PostId,
                    AuthorName = x.AuthorName,
                    CreatedOn = x.CreatedOn,
                    Content = x.Text
                })
            };

            return View(model);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult EditPost(PostEditModel model)
        {
            if (ModelState.IsValid)
            {
                postService.UpdatePost(model.Id, model.Location, model.Content);

                return RedirectToAction("EditPost", model.Id);
            }

            return View(model);
        }

        [HttpPut, ValidateAntiForgeryToken]
        public IActionResult UpdateComment(CommentInputModel model)
        {
            commentService.UpdateComment(model.PostId, model.Id, model.Content);

            return Ok("Updated");
        }

        [HttpPost, ValidateAntiForgeryToken] // HTML form.submit does not bind with DELETE method
        public IActionResult DeletePost(int id)
        {
            postService.DeletePost(id);

            return RedirectToAction("index", "newsfeed");
        }

        [HttpDelete, ValidateAntiForgeryToken]
        public IActionResult DeleteComment(CommentInputModel model)
        {
            commentService.DeleteComment(model.PostId, model.Id);

            return Ok("Deleted");
        }

        [HttpDelete]
        public IActionResult DeletePhoto(int postId, int photoId)
        {
            postService.DeletePostPhoto(postId, photoId);

            return Ok("Deleted");
        }
    }
}

ConnectIT.Web/Controllers/FriendController.cs
using ConnectIT.Services.Contracts;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ConnectIT.Web.Controllers
{
    public class FriendController : Controller
    {
        private readonly IFriendService friendService;
        private readonly IUserService userService;

        public FriendController(IFriendService friendService, IUserService userService)
        {
            this.friendService = friendService;
            this.userService = userService;
        }

        [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
        public IActionResult Index()
        {

            var userId = User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier).Value;

            var users = this.friendService.GetFriends(userId);

            return View(users);

        }

        [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
        public IActionResult RemoveFriend(string senderId, string receiverId)
        {
           
            senderId = User.Claims.First(x => x.Type == ClaimTypes.NameIdentifier).Value;
            this.friendService.RemoveFriend(receiverId, senderId);
            TempData["message"] = "Friend Removed";
            return RedirectToAction(nameof(Index));
        }




    }
}

ConnectIT.Web/Controllers/UsersController.cs
using ConnectIT.DataTransfer;
using ConnectIT.Services.Contracts;
using ConnectIT.Web.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Linq;

namespace ConnectIT.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService userService;

        public UsersController(IUserService userService)
        {
            this.userService = userService;
        }

        public IActionResult Index(UserListModel model, string searchBy, string searchString)
        {
            if (model == null)
            {
                model = new UserListModel();
            }
            model.Users = this.userService.GetUsers().Select(user => new UserSummaryModel(user));

            if (searchBy == "Name")
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    model.Users = model.Users.Where(s => s.FullName.ToLower().Contains(searchString.ToLower()));
                }
            }

            if (searchBy == "Job")
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    model.Users = model.Users.Where(t => t.Job != null && t.Job.ToLower().Contains(searchString.ToLower()));
                }
            }

            return View(model);
        }

        public IActionResult Details(string id)
        {
            var dto = this.userService.GetUserById(id);
            var model = new UserSummaryModel(dto);
            return View(model);
        }

        // GET: users/list
        [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
        [Authorize(Roles = "admin"), HttpGet]
        public IActionResult List()
        {
            var users = this.userService.GetUsersIncludingDeleted();

            return View(users);
        }

        [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
        [Authorize(Roles = "admin")]
        public IActionResult DeleteUser([FromForm] string userId)
        {
            this.userService.DeleteUser(userId);
            return RedirectToAction(nameof(List));
        }

        [Authorize(Roles = "admin")]
        public IActionResult RestoreUser(string userId)
        {
            this.userService.RestoreUser(userId);
            return RedirectToAction(nameof(List));
        }

        [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
        [Authorize(Roles = "admin")]
        public IActionResult Edit(string Id)
        {
            var dto = userService.GetOneUserbyId(Id);
            var model = new UserEditModel(dto);

            return View(model);
        }

        [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
        [HttpPost]
        [ValidateAntiForgeryToken]

        [Authorize(Roles = "admin")]
        public IActionResult Edit(string Id, UserDetail model)
        {
            if (ModelState.IsValid)
            {

                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var dataStream = new MemoryStream())
                    {
                        file.CopyTo(dataStream);

                        model.ProfilePhoto = dataStream.ToArray();

                    }
                }

                userService.UpdateUser(model);
                TempData["message"] = "User Details Updated";
                return RedirectToAction("Edit");
            }

            return View(model);
        }
    }
}

ConnectIT.Web/Controllers/WallController.cs
using ConnectIT.DataTransfer;
using ConnectIT.Services.Contracts;
using ConnectIT.Web.Models;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Security.Claims;

namespace ConnectIT.Web.Controllers
{
    [Authorize(AuthenticationSchemes = "Identity.Application," + JwtBearerDefaults.AuthenticationScheme)]
    public class WallController : Controller
    {
        private readonly IPostService postService;
        private readonly IFriendService friendService;

        public WallController(IPostService postService, IFriendService friendService)
        {
            this.postService = postService;
            this.friendService = friendService;
        }

        private string UserId => User.FindFirstValue(ClaimTypes.NameIdentifier);

        // GET: wall
        [HttpGet]
        public IActionResult Index()
        {
            return View(postService.GetWall(UserId));
        }

        // GET: wall/partial/id
        [HttpGet("wall/partial/{postId}")]
        public IActionResult GetOlderPosts(int postId)
        {
            return PartialView("_PostCollectionPartial", postService.GetWall(UserId, postId));
        }

        // GET: wall/create
        public IActionResult Create()
        {
            var model = new PostInputModel();

            model.Friends = friendService.GetFriends(UserId)
                .Select(x => new SelectListItem($"{x.FirstName} {x.LastName}", x.Id));

            return View(model);
        }

        // POST: wall/create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PostInputModel model)
        {
            if (ModelState.IsValid)
            {
                model.AuthorId = UserId;

                postService.CreatePost((PostDetail)model);

                return RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

ConnectIT.Web/Views/Shared/_CommentCollectionPartial.cshtml
@model IEnumerable<CommentDetail>
@foreach (var comment in Model.Take(3))
{
    <partial name="_CommentPartial" for="@comment" />
}

@if (Model.Count() > 3)
{
    var modalId = "comments-modal-" + ViewData["PostId"];
    <button class="btn badge badge-pill btn-outline-info mt-2" data-toggle="modal" data-target="#@modalId">
        <img src="/assets/chat-text.svg" width="16" height="16" />
        <span>+ @Model.Skip(3).Count()</span>
    </button>
    <div id="@modalId" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @foreach (var comment in Model)
                    {
                        <partial name="_CommentPartial" for="@comment" />
                    }
                </div>
            </div>
        </div>
    </div>
}

ConnectIT.Web/Views/Shared/_CommentPartial.cshtml
@model CommentDetail
<div class="w-100 border-bottom border-info">
    <i>By @Model.AuthorName on @Model.CreatedOn.ToDisplayFormat()</i>
    <p class="mb-2">@Model.Text</p>
</div>

ConnectIT.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ConnectIT</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="NewsFeed" asp-action="Index">ConnectIT</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated && !User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Wall" asp-action="Index">Wall</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="FriendRequest" asp-action="Index">Friend Requests</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Friend" asp-action="Index">Friends</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">Users</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="/swagger">Swagger</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="List">Manage Users</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ConnectIT.Web/Views/Shared/_PostCollectionPartial.cshtml
@model IEnumerable<PostDetail>
@foreach (var post in Model)
{
    <partial name="_PostPartial" for="@post" />
}

ConnectIT.Web/Views/Shared/_PostPartial.cshtml
@model PostDetail
@{
    ViewData.Add("PostId", Model.Id);

    var headerText = Model.Author.FullName;

    if (Model.TaggedFriends.Any())
        headerText += " with " + string.Join(", ", Model.TaggedFriends.Select(x => x.FullName));

    if (Model.Location != null)
        headerText += " at " + Model.Location;

    headerText += " on " + Model.CreatedOn.ToDisplayFormat();
}
<div data-post-id="@Model.Id" class="card">
    <div class="card-header">
        @if (User.IsInRole("admin"))
        {
            @Html.ActionLink("Edit", "EditPost", "Admin", new { id = Model.Id }, new { @class = "btn badge badge-pill btn-info" })
        }
        @headerText
    </div>
    <div class="card-body">
        @Model.Content
    </div>
    @if (Model.Photos.Any())
    {
        <div class="position-relative">
            <img class="card-img" src="data:image;base64,@Model.Photos.First().ToBase64()" />
            @if (Model.Photos.Count() > 1)
            {
                <button class="btn btn-outline-info position-absolute" style="bottom:5%;right:5%" data-toggle="modal" data-target="#gallery-@Model.Id">
                    + @Model.Photos.Skip(1).Count()
                </button>
                <!-- Gallery Modal -->
                <div id="gallery-@Model.Id" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body card-deck">
                                @foreach (var photo in Model.Photos.Skip(1))
                                {
                                    <img class="card-img pb-3 px-lg-3" src="data:image;base64,@photo.ToBase64()" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
    <div class="card-footer">
        <partial name="_ReactionCollectionPartial" for="@Model.Reactions" view-data="ViewData" />
        <div id="comments-@Model.Id" class="mt-2">
            <partial name="_CommentCollectionPartial" for="@Model.Comments" view-data="ViewData" />
        </div>
    </div>
</div>

ConnectIT.Web/Views/Shared/_ReactionCollectionPartial.cshtml
@using System.Security.Claims;

@model IEnumerable<ReactionDetail>

@if (User.Identity.IsAuthenticated)
{
    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
    var postId = (int)ViewData["PostId"];

    <button class="@Model.GetReactionStyles(userId, 0)" data-code="0" onclick="userInteraction.toggleReaction($(this), @postId)">
        <img src="/assets/hand-thumbs-up.svg" width="16" height="16" />
        <span>@Model.CountWithCode(0)</span>
    </button>
    <button class="@Model.GetReactionStyles(userId, 1)" data-code="1" onclick="userInteraction.toggleReaction($(this), @postId)">
        <img src="/assets/heart.svg" width="16" height="16" />
        <span>@Model.CountWithCode(1)</span>
    </button>
    <button class="@Model.GetReactionStyles(userId, 2)" data-code="2" onclick="userInteraction.toggleReaction($(this), @postId)">
        <img src="/assets/emoji-laughing.svg" width="16" height="16" />
        <span>@Model.CountWithCode(2)</span>
    </button>
    <button class="@Model.GetReactionStyles(userId, 3)" data-code="3" onclick="userInteraction.toggleReaction($(this), @postId)">
        <img src="/assets/emoji-angry.svg" width="16" height="16" />
        <span>@Model.CountWithCode(3)</span>
    </button>
    <button class="@Styles.StandardBadgeStyles" onclick="userInteraction.createComment(@postId)">
        <img src="/assets/pencil.svg" width="16" height="16" />
        <span>Comment</span>
    </button>
}
else
{
    <label class="badge badge-pill border border-info">
        <img src="/assets/hand-thumbs-up.svg" width="16" height="16" />
        <span>@Model.CountWithCode(0)</span>
    </label>
    <label class="badge badge-pill border border-info">
        <img src="/assets/heart.svg" width="16" height="16" />
        <span>@Model.CountWithCode(1)</span>
    </label>
    <label class="badge badge-pill border border-info">
        <img src="/assets/emoji-laughing.svg" width="16" height="16" />
        <span>@Model.CountWithCode(2)</span>
    </label>
    <label class="badge badge-pill border border-info">
        <img src="/assets/emoji-angry.svg" width="16" height="16" />
        <span>@Model.CountWithCode(3)</span>
    </label>
}

ConnectIT.Web/Views/Shared/_UserPartial.cshtml
@model ConnectIT.DataTransfer.UserSummary

@{

}
<div>
    <h3>
        @if (Model.ProfilePhoto != null)
        {<img class="rounded-circle" src="data:image;base64,@Convert.ToBase64String(Model.ProfilePhoto)" width="33" height="33" />
        } @Model.FirstName @Model.LastName
    </h3>
</div>